/**
 * Audio Source Resolver Service
 * 
 * Smart service that resolves audio sources for Bible chapters
 * Priority: Local files > WordProject CDN > Fallback
 * 
 * Features:
 * - Check local file existence
 * - Generate WordProject URLs
 * - Track audio sources in database
 * - Support both Persian (fa) and English (en)
 */

const fs = require('fs');
const path = require('path');

class AudioSourceResolver {
  constructor() {
    // Base paths for local audio files
    this.localBasePath = path.join(__dirname, '../../public/audio/bible');
    this.autoGeneratedPath = path.join(this.localBasePath, 'auto-generated');
    this.wordprojectPath = path.join(this.localBasePath, 'wordproject');
    
    // Production server URL (where files are deployed)
    this.productionServerUrl = process.env.PRODUCTION_SERVER_URL || 'https://195.250.25.185';
    
    // WordProject CDN base URL
    this.wordprojectBaseUrl = 'https://www.wordproject.org/bibles/audio_fa';
    
    // Book code to WordProject number mapping (1-66)
    this.bookToNumberMap = {
      // Old Testament
      'GEN': '01', 'EXO': '02', 'LEV': '03', 'NUM': '04', 'DEU': '05',
      'JOS': '06', 'JDG': '07', 'RUT': '08', '1SA': '09', '2SA': '10',
      '1KI': '11', '2KI': '12', '1CH': '13', '2CH': '14', 'EZR': '15',
      'NEH': '16', 'EST': '17', 'JOB': '18', 'PSA': '19', 'PRO': '20',
      'ECC': '21', 'SNG': '22', 'ISA': '23', 'JER': '24', 'LAM': '25',
      'EZK': '26', 'DAN': '27', 'HOS': '28', 'JOL': '29', 'AMO': '30',
      'OBA': '31', 'JON': '32', 'MIC': '33', 'NAM': '34', 'HAB': '35',
      'ZEP': '36', 'HAG': '37', 'ZEC': '38', 'MAL': '39',
      // New Testament
      'MAT': '40', 'MRK': '41', 'LUK': '42', 'JHN': '43', 'ACT': '44',
      'ROM': '45', '1CO': '46', '2CO': '47', 'GAL': '48', 'EPH': '49',
      'PHP': '50', 'COL': '51', '1TH': '52', '2TH': '53', '1TI': '54',
      '2TI': '55', 'TIT': '56', 'PHM': '57', 'HEB': '58', 'JAS': '59',
      '1PE': '60', '2PE': '61', '1JN': '62', '2JN': '63', '3JN': '64',
      'JUD': '65', 'REV': '66'
    };
  }

  /**
   * Resolve best audio source for a Bible chapter
   * @param {string} bookCode - 3-letter book code (e.g., 'GEN', 'MAT')
   * @param {number} chapter - Chapter number
   * @param {string} language - Language code ('fa' or 'en')
   * @returns {Promise<Object>} Audio source object
   */
  async resolveAudioSource(bookCode, chapter, language = 'fa') {
    const result = {
      success: false,
      bookCode,
      chapter,
      language,
      sources: [],
      primary: null,
      metadata: {}
    };

    try {
      // 1. Check Edge TTS folder (newest high-quality source) - HIGHEST PRIORITY  
      const edgeTtsSource = await this.checkEdgeTTS(bookCode, chapter, language);
      if (edgeTtsSource) {
        result.sources.push(edgeTtsSource);
        if (!result.primary) result.primary = edgeTtsSource;
      }
      
      // 2. Check auto-generated (Edge TTS legacy)
      const autoGenSource = await this.checkAutoGenerated(bookCode, chapter, language);
      if (autoGenSource) {
        result.sources.push(autoGenSource);
        if (!result.primary) result.primary = autoGenSource;
      }

      // 3. Check local WordProject downloads
      const localWordprojectSource = await this.checkLocalWordProject(bookCode, chapter, language);
      if (localWordprojectSource) {
        result.sources.push(localWordprojectSource);
        if (!result.primary) result.primary = localWordprojectSource;
      }

      // 4. Generate WordProject CDN URL (always available as fallback)
      const wordprojectCdnSource = this.generateWordProjectUrl(bookCode, chapter, language);
      if (wordprojectCdnSource) {
        result.sources.push(wordprojectCdnSource);
        if (!result.primary) result.primary = wordprojectCdnSource;
      }

      result.success = result.sources.length > 0;
      
      // Add metadata
      if (result.primary) {
        result.metadata = {
          sourceType: result.primary.type,
          isLocal: result.primary.isLocal,
          url: result.primary.url,
          fileSize: result.primary.fileSize || 'unknown',
          estimatedDuration: result.primary.duration || 'unknown'
        };
      }

      return result;

    } catch (error) {
      console.error('❌ Error resolving audio source:', error);
      result.error = error.message;
      return result;
    }
  }

  /**
   * Check if Edge TTS file exists (new folder structure)
   */
  async checkEdgeTTS(bookCode, chapter, language) {
    // Check: /audio/bible/edge-tts/BOOK/chapter.mp3
    const filename = `${chapter}.mp3`;
    const filepath = path.join(this.localBasePath, 'edge-tts', bookCode, filename);

    if (fs.existsSync(filepath)) {
      const stats = fs.statSync(filepath);
      
      // Check if running in production (files on remote server)
      const isProduction = process.env.NODE_ENV === 'production';
      const baseUrl = isProduction ? this.productionServerUrl : '';
      
      return {
        type: 'edge-tts',
        source: 'Edge TTS (High Quality)',
        isLocal: !isProduction,
        url: `${baseUrl}/audio/bible/edge-tts/${bookCode}/${filename}`,
        absolutePath: filepath,
        fileSize: stats.size,
        fileSizeMB: (stats.size / (1024 * 1024)).toFixed(2),
        exists: true,
        priority: 1, // Highest priority
        quality: 'high'
      };
    }

    return null;
  }

  /**
   * Check if auto-generated (Edge TTS) file exists
   */
  async checkAutoGenerated(bookCode, chapter, language) {
    const filename = `${bookCode}_${chapter}_${language}.mp3`;
    const filepath = path.join(this.autoGeneratedPath, filename);

    if (fs.existsSync(filepath)) {
      const stats = fs.statSync(filepath);
      
      // Check if running in production (files on remote server)
      const isProduction = process.env.NODE_ENV === 'production';
      const baseUrl = isProduction ? this.productionServerUrl : '';
      
      return {
        type: 'auto-generated',
        source: 'Edge TTS',
        isLocal: !isProduction,
        url: `${baseUrl}/audio/bible/auto-generated/${filename}`,
        absolutePath: filepath,
        fileSize: stats.size,
        fileSizeMB: (stats.size / (1024 * 1024)).toFixed(2),
        exists: true,
        priority: 1 // Highest priority
      };
    }

    return null;
  }

  /**
   * Check if local WordProject download exists
   */
  async checkLocalWordProject(bookCode, chapter, language) {
    const bookNumber = this.bookToNumberMap[bookCode];
    if (!bookNumber) return null;

    const filename = `${chapter}.mp3`;
    const filepath = path.join(this.wordprojectPath, bookNumber, filename);

    if (fs.existsSync(filepath)) {
      const stats = fs.statSync(filepath);
      
      // Check if running in production
      const isProduction = process.env.NODE_ENV === 'production';
      const baseUrl = isProduction ? this.productionServerUrl : '';
      
      return {
        type: 'wordproject-local',
        source: 'WordProject (Downloaded)',
        isLocal: !isProduction,
        url: `${baseUrl}/audio/bible/wordproject/${bookNumber}/${filename}`,
        absolutePath: filepath,
        fileSize: stats.size,
        fileSizeMB: (stats.size / (1024 * 1024)).toFixed(2),
        exists: true,
        priority: 2
      };
    }

    return null;
  }

  /**
   * Generate WordProject CDN URL (always available)
   */
  generateWordProjectUrl(bookCode, chapter, language) {
    const bookNumber = this.bookToNumberMap[bookCode];
    if (!bookNumber) return null;

    // WordProject URL format: https://www.wordproject.org/bibles/audio_fa/01/1.mp3
    const url = `${this.wordprojectBaseUrl}/${bookNumber}/${chapter}.mp3`;

    return {
      type: 'wordproject-cdn',
      source: 'WordProject CDN',
      isLocal: false,
      url: url,
      exists: 'unknown', // Will be verified when accessed
      priority: 3, // Lowest priority (fallback)
      note: 'Streaming from WordProject CDN'
    };
  }

  /**
   * Get audio source for multiple chapters (batch)
   */
  async resolveMultipleChapters(bookCode, chapters, language = 'fa') {
    const promises = chapters.map(chapter => 
      this.resolveAudioSource(bookCode, chapter, language)
    );
    return await Promise.all(promises);
  }

  /**
   * Get inventory of all available local audio files
   */
  async getLocalInventory() {
    const inventory = {
      autoGenerated: [],
      wordprojectDownloads: [],
      totalFiles: 0,
      totalSizeMB: 0
    };

    try {
      // Scan auto-generated directory
      if (fs.existsSync(this.autoGeneratedPath)) {
        const files = fs.readdirSync(this.autoGeneratedPath).filter(f => f.endsWith('.mp3'));
        
        for (const file of files) {
          const filepath = path.join(this.autoGeneratedPath, file);
          const stats = fs.statSync(filepath);
          const match = file.match(/^([A-Z0-9]+)_(\d+)_(fa|en)\.mp3$/);
          
          if (match) {
            inventory.autoGenerated.push({
              filename: file,
              bookCode: match[1],
              chapter: parseInt(match[2]),
              language: match[3],
              size: stats.size,
              sizeMB: (stats.size / (1024 * 1024)).toFixed(2)
            });
            inventory.totalSizeMB += stats.size;
          }
        }
      }

      // Scan WordProject downloads directory
      if (fs.existsSync(this.wordprojectPath)) {
        const bookDirs = fs.readdirSync(this.wordprojectPath, { withFileTypes: true })
          .filter(dirent => dirent.isDirectory());

        for (const bookDir of bookDirs) {
          const bookPath = path.join(this.wordprojectPath, bookDir.name);
          const files = fs.readdirSync(bookPath).filter(f => f.endsWith('.mp3'));

          for (const file of files) {
            const filepath = path.join(bookPath, file);
            const stats = fs.statSync(filepath);
            const chapter = parseInt(file.replace('.mp3', ''));

            inventory.wordprojectDownloads.push({
              filename: file,
              bookNumber: bookDir.name,
              chapter: chapter,
              size: stats.size,
              sizeMB: (stats.size / (1024 * 1024)).toFixed(2)
            });
            inventory.totalSizeMB += stats.size;
          }
        }
      }

      inventory.totalFiles = inventory.autoGenerated.length + inventory.wordprojectDownloads.length;
      inventory.totalSizeMB = (inventory.totalSizeMB / (1024 * 1024)).toFixed(2);

      return inventory;

    } catch (error) {
      console.error('❌ Error getting local inventory:', error);
      return inventory;
    }
  }

  /**
   * Check if audio exists for a specific chapter
   */
  async audioExists(bookCode, chapter, language = 'fa') {
    const result = await this.resolveAudioSource(bookCode, chapter, language);
    return result.success && result.primary && result.primary.isLocal;
  }
}

module.exports = new AudioSourceResolver();
