<#
  Apply HiDrive URL migration to production PostgreSQL database.
  Steps:
    1. Upload hidrive-url-migration.sql to server
    2. Create a compressed pre-migration backup (pg_dump -Fc)
    3. Run the SQL file
    4. Verify sample updated rows

  Usage:
    powershell -File .\apply-hidrive-url-migration.ps1 

  Requirements:
    - SSH access to server (root@samanabyar.online) with key or password
    - Server has psql/pg_dump installed and correct PATH
    - Ensure hidrive-url-migration.sql exists locally (generated by migrate-to-hidrive.ps1 -Mode update-db)

  Rollback plan:
    pg_restore -U myuser -d mychurch /root/db-backups/pre-hidrive-urls.dump
#>

$ErrorActionPreference = 'Stop'

# --- Config ---
$Server = 'root@samanabyar.online'
$RemoteBase = '/root/Mychurch'
$RemoteSQLDir = "$RemoteBase/backend/db"
$DBUser = 'myuser'
$DBName = 'mychurch'
$BackupDir = '/root/db-backups'
$LocalSqlFile = 'hidrive-url-migration.sql'
$Timestamp = (Get-Date -Format 'yyyyMMdd_HHmmss')
$BackupFileName = "pre-hidrive-urls-$Timestamp.dump"

Write-Host "=== Apply HiDrive URL Migration ===" -ForegroundColor Cyan

if (!(Test-Path $LocalSqlFile)) {
  Write-Host "Missing $LocalSqlFile. Generate it first with migrate-to-hidrive.ps1 -Mode update-db" -ForegroundColor Red
  exit 1
}

Write-Host "Step 1: Upload SQL file" -ForegroundColor Yellow
ssh $Server "mkdir -p $RemoteSQLDir" | Out-Null
scp $LocalSqlFile "${Server}:$RemoteSQLDir/"
Write-Host "Uploaded $LocalSqlFile to $RemoteSQLDir" -ForegroundColor Green

Write-Host "Step 2: Pre-migration backup" -ForegroundColor Yellow
$BackupCmd = "mkdir -p $BackupDir && pg_dump -U $DBUser -d $DBName -Fc -f $BackupDir/$BackupFileName"
ssh $Server $BackupCmd
Write-Host "Backup created: $BackupDir/$BackupFileName" -ForegroundColor Green

Write-Host "Step 3: Execute migration SQL" -ForegroundColor Yellow
$ExecuteCmd = "cd $RemoteSQLDir && psql -U $DBUser -d $DBName -f $RemoteSQLDir/$LocalSqlFile"
ssh $Server $ExecuteCmd
Write-Host "Migration SQL executed" -ForegroundColor Green

Write-Host "Step 4: Verification queries" -ForegroundColor Yellow
$VerifyCmd = @(
  ("psql -U {0} -d {1} -c 'SELECT id, audiourl FROM worship_songs WHERE audiourl LIKE ''https://webdav.hidrive.ionos.com/%'' LIMIT 3;'" -f $DBUser, $DBName),
  ("psql -U {0} -d {1} -c 'SELECT id, audiourl FROM sermons WHERE audiourl LIKE ''https://webdav.hidrive.ionos.com/%'' LIMIT 3;'" -f $DBUser, $DBName),
  ("psql -U {0} -d {1} -c 'SELECT id, imageurl FROM events WHERE imageurl LIKE ''https://webdav.hidrive.ionos.com/%'' LIMIT 3;'" -f $DBUser, $DBName)
)
foreach ($cmd in $VerifyCmd) { ssh $Server $cmd }
Write-Host "Verification complete" -ForegroundColor Green

Write-Host "=== Migration Finished ===" -ForegroundColor Cyan
Write-Host "If rollback needed:" -ForegroundColor Yellow
Write-Host "  pg_restore -U $DBUser -d $DBName $BackupDir/$BackupFileName" -ForegroundColor Gray
