server {
    listen 80;
    listen [::]:80;
    server_name samanabyar.online www.samanabyar.online;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name samanabyar.online www.samanabyar.online;

    ssl_certificate /etc/letsencrypt/live/samanabyar.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/samanabyar.online/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }

    # Serve uploads directly
    location /uploads/ {
        alias /root/mychurch-v2/public/uploads/;
        add_header Cache-Control "public, max-age=31536000";
    }

    # Intercept old HiDrive DB links and serve them LOCALLY with zero latency!
    location ~ ^/api/hidrive/stream/worship/audio/(.*)$ {
        alias /root/mychurch-v2/public/uploads/audio/$1;
        add_header Cache-Control "public, max-age=31536000";
    }
}
