/**
 * Audio Routes
 * 
 * API endpoints for Bible audio management
 * - Get audio source for a chapter
 * - Get audio inventory
 * - Download audio from WordProject
 */

const express = require('express');
const router = express.Router();
const audioSourceResolver = require('../services/audioSourceResolver');

/**
 * GET /api/audio/source/:book/:chapter
 * Get best audio source for a Bible chapter
 * 
 * Query params:
 * - lang: 'fa' or 'en' (default: 'fa')
 * 
 * Response:
 * {
 *   success: true,
 *   bookCode: "GEN",
 *   chapter: 1,
 *   language: "fa",
 *   sources: [...],
 *   primary: { type, url, isLocal, ... },
 *   metadata: { sourceType, fileSize, ... }
 * }
 */
router.get('/source/:book/:chapter', async (req, res) => {
  try {
    const { book, chapter } = req.params;
    const { lang = 'fa' } = req.query;

    // Validate inputs
    if (!book || !chapter) {
      return res.status(400).json({
        success: false,
        error: 'Book code and chapter number are required'
      });
    }

    const chapterNum = parseInt(chapter);
    if (isNaN(chapterNum) || chapterNum < 1) {
      return res.status(400).json({
        success: false,
        error: 'Invalid chapter number'
      });
    }

    // Resolve audio source
    const result = await audioSourceResolver.resolveAudioSource(
      book.toUpperCase(),
      chapterNum,
      lang
    );

    if (!result.success) {
      return res.status(404).json({
        success: false,
        error: 'No audio source found',
        bookCode: book.toUpperCase(),
        chapter: chapterNum
      });
    }

    res.json(result);

  } catch (error) {
    console.error('❌ Error getting audio source:', error);
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
});

/**
 * GET /api/audio/source/:book/:chapter/verify
 * Verify if audio exists (quick check)
 */
router.get('/source/:book/:chapter/verify', async (req, res) => {
  try {
    const { book, chapter } = req.params;
    const { lang = 'fa' } = req.query;

    const exists = await audioSourceResolver.audioExists(
      book.toUpperCase(),
      parseInt(chapter),
      lang
    );

    res.json({
      success: true,
      bookCode: book.toUpperCase(),
      chapter: parseInt(chapter),
      language: lang,
      exists,
      localFile: exists
    });

  } catch (error) {
    console.error('❌ Error verifying audio:', error);
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
});

/**
 * GET /api/audio/inventory
 * Get full inventory of local audio files
 */
router.get('/inventory', async (req, res) => {
  try {
    const inventory = await audioSourceResolver.getLocalInventory();

    res.json({
      success: true,
      inventory,
      summary: {
        totalFiles: inventory.totalFiles,
        totalSizeMB: inventory.totalSizeMB,
        autoGenerated: inventory.autoGenerated.length,
        wordprojectDownloads: inventory.wordprojectDownloads.length
      }
    });

  } catch (error) {
    console.error('❌ Error getting inventory:', error);
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
});

/**
 * POST /api/audio/batch-resolve
 * Resolve audio sources for multiple chapters at once
 * 
 * Body:
 * {
 *   bookCode: "GEN",
 *   chapters: [1, 2, 3, ...],
 *   language: "fa"
 * }
 */
router.post('/batch-resolve', async (req, res) => {
  try {
    const { bookCode, chapters, language = 'fa' } = req.body;

    if (!bookCode || !chapters || !Array.isArray(chapters)) {
      return res.status(400).json({
        success: false,
        error: 'bookCode and chapters array are required'
      });
    }

    const results = await audioSourceResolver.resolveMultipleChapters(
      bookCode.toUpperCase(),
      chapters,
      language
    );

    res.json({
      success: true,
      bookCode: bookCode.toUpperCase(),
      language,
      totalChapters: chapters.length,
      results
    });

  } catch (error) {
    console.error('❌ Error batch resolving:', error);
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
});

/**
 * GET /api/audio/stats
 * Get audio statistics
 */
router.get('/stats', async (req, res) => {
  try {
    const inventory = await audioSourceResolver.getLocalInventory();

    // Calculate stats
    const stats = {
      totalAudioFiles: inventory.totalFiles,
      totalStorageUsed: `${inventory.totalSizeMB} MB`,
      bySource: {
        edgeTTS: {
          count: inventory.autoGenerated.length,
          books: [...new Set(inventory.autoGenerated.map(f => f.bookCode))].length
        },
        wordproject: {
          count: inventory.wordprojectDownloads.length,
          books: [...new Set(inventory.wordprojectDownloads.map(f => f.bookNumber))].length
        }
      },
      byLanguage: {
        persian: inventory.autoGenerated.filter(f => f.language === 'fa').length,
        english: inventory.autoGenerated.filter(f => f.language === 'en').length
      }
    };

    res.json({
      success: true,
      stats
    });

  } catch (error) {
    console.error('❌ Error getting stats:', error);
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
});

module.exports = router;
