-- migrations/add_audio_timing_support.sql
-- Migration to add audio timing support for worship songs and Bible chapters

-- Add timing columns to worship_songs table
ALTER TABLE worship_songs 
ADD COLUMN IF NOT EXISTS timing_data JSONB DEFAULT NULL,
ADD COLUMN IF NOT EXISTS timing_updated_at TIMESTAMP DEFAULT NULL;

-- Create bible_audio_timing table
CREATE TABLE IF NOT EXISTS bible_audio_timing (
  id SERIAL PRIMARY KEY,
  book_code VARCHAR(10) NOT NULL,
  chapter INTEGER NOT NULL,
  translation VARCHAR(50) NOT NULL,
  timing_data JSONB NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(book_code, chapter, translation)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_worship_timing ON worship_songs(timing_updated_at) WHERE timing_data IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_bible_timing_lookup ON bible_audio_timing(book_code, chapter, translation);

-- Comments
COMMENT ON COLUMN worship_songs.timing_data IS 'JSON array of word-level timestamps generated by Gemini AI';
COMMENT ON COLUMN worship_songs.timing_updated_at IS 'Last time timing data was generated/updated';
COMMENT ON TABLE bible_audio_timing IS 'Stores verse and word-level timing data for Bible audio chapters';

COMMIT;
